### ISSUE TITLE
Practica Diagrama De Secuencias

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-equipo-exe#1]
[Diagrama Secuencial Oaxaqueando.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-equipo-exe/files/7824375/Diagrama.Secuencial.Oaxaqueando.pdf)

**Comment by KarlaV0** [comment]
30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
